import Head from 'next/head'
import { Inter } from 'next/font/google'
import HomeComponent from '@/components/pages/Home'
import AboutComponent from '@/components/pages/About'
import ServicesComponent from '@/components/pages/Services'
import SkillsComponent from '@/components/pages/Skills'
import EducationComponent from '@/components/pages/Education'
import ExperienceComponent from '@/components/pages/Experience'
import ContactComponent from '@/components/pages/Contact'
import Referencer from '@/components/pages/Referencer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sudarshan Khadka</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <HomeComponent/>
        <AboutComponent/>
        <ServicesComponent/>
        <SkillsComponent/>
        <EducationComponent/>
        <ExperienceComponent/>
        <Referencer/>
        <ContactComponent/>
    </>
  )
}
